#pragma once

#include <vector>
#include "../types.h"
#include "./algorithms/localSearch.hpp"
#include "./algorithms/neighbourhoods/tsp.hpp"
#include "./algorithms/neighbourhoods/clustering.hpp"
#include "./algorithms/neighbourhoods/maxsat.hpp"
#include "../algorithm/observers/AlgorithmObserver.hpp"
#include "../data/solution_container/tsp.hpp"
#include "../data/solution_container/clustering.hpp"
#include "../data/solution_container/maxsat.hpp"
#include "../algorithm/swaps/tsp.hpp"
#include "../algorithm/swaps/clustering.hpp"
#include "../algorithm/swaps/maxsat.hpp"
#include "../data/constants/tsp.hpp"
#include "../data/constants/clustering.hpp"
#include "../data/constants/maxsat.hpp"
#include "../utils.h"
