#!/bin/bash
#SBATCH --output=log-%x-%j.out
#SBATCH --error=log-%x-%j.err
#SBATCH --nodes=1
#SBATCH --cpus-per-task=64
#SBATCH --time=3-00:00:00
#SBATCH --mem=8G

module load python/3.9
pip install numpy pandas --no-index
# Capture the start time
start_time=$(date +"%Y-%m-%d %H:%M:%S")

/scratch/rmoine/FIBI/FIBI -path_out /scratch/rmoine/FIBI/out/dataset$SLURM_JOB_ID\.txt -root_data /scratch/rmoine/FIBI/data/folder/ -dataset 0 -n_treads 64 -impr 0 -seed_start 15600 -seed_end 20800 -problem tsp -num_rep 1000 -opt 3 -do_missings 2 -root /scratch/rmoine/FIBI/

# Capture the end time
end_time=$(date +"%Y-%m-%d %H:%M:%S")

# Calculate and display the execution time
start_seconds=$(date -d "$start_time" '+%s')
end_seconds=$(date -d "$end_time" '+%s')
execution_time=$((end_seconds - start_seconds))

echo "Execution time: $execution_time seconds"
