#!/bin/bash
#SBATCH --output=log-check.out
#SBATCH --error=log-check.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:10:00
# Capture the start time
start_time=$(date +"%Y-%m-%d %H:%M:%S")

module use /usr/local/src/spack/share/spack/modules/linux-ubuntu20.04-zen2
module avail
module load python-3.9.15-gcc-9.4.0-5jyuh3b
module load py-numpy-1.24.1-gcc-9.4.0-mtejhor
module load py-pandas/1.5.3-gcc-9.4.0-ohbmp5n

# Start the script
python check.py  ../out/merged_dataset.txt


# Capture the end time
end_time=$(date +"%Y-%m-%d %H:%M:%S")

# Calculate and display the execution time
start_seconds=$(date -d "$start_time" '+%s')
end_seconds=$(date -d "$end_time" '+%s')
execution_time=$((end_seconds - start_seconds))

echo "Execution time: $execution_time seconds"
